---
- project:
    name: common-dataservice-config-management-project
    project-name: common-dataservice-config-management
    project: common-dataservice/config-management
    build-node: centos7-docker-4c-4g
    mvn-settings: common-dataservice-config-management-settings
    python-version: python3
    build-timeout: 30
    concurrent: false
    container-tag-method: yaml-file
    docker-name: acumos/config-management
    # use host network
    docker-build-args: '--network=host'
    jobs:
      - '{project-name}-python-jobs'
      - '{project-name}-gerrit-docker-jobs'
    stream:
      - master:
          branch: master
      # no athena stream needed

- project:
    name: common-dataservice-config-management-sonar
    project-name: common-dataservice-config-management
    project: common-dataservice/config-management
    mvn-settings: common-dataservice-config-management-settings
    build-node: centos7-avx-4c-4g
    jobs:
      - gerrit-maven-sonar
    cron: 'H 11 * * *'
    branch: 'master'
    mvn-goals: 'clean install'
    mvn-opts: '-Xmx1024m -XX:MaxPermSize=256m'
